In [ ]:
import pandas as pd

In [6]:
headers = ["symboling",
           "normalized-losses",
           "make",
           "fuel-type",
           "aspiration",
           "num-of-doors",
           "body-style",
           "drive-wheels",
           "engine-location",
           "wheel-base",
           "length",
           "width",
           "height",
           "curb-weight",
           "engine-type",
           "num-of-cylinders",
           "engine-size",
           "fuel-system",
           "bore", "stroke",
           "compression-ratio",
           "horsepower",
           "peak-rpm",
           "city-mpg",
           "highway-mpg",
           "price"]

df = pd.read_csv("data.csv", names=headers)

In [7]:
price = df["price"]

In [8]:
type(price)

pandas.Series

In [9]:
type(df)

pandas.DataFrame

In [10]:
df[['highway-mpg', 'engine-size', 'price']]

     highway-mpg  engine-size  price
0             27          130  13495
1             27          130  16500
2             26          152  16500
3             30          109  13950
4             22          136  17450
..           ...          ...    ...
200           28          141  16845
201           25          141  19045
202           23          173  21485
203           27          145  22470
204           25          141  22625

[205 rows x 3 columns]

In [11]:
df.select_dtypes(include='number')

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
0,3,88.6,168.8,64.1,48.8,2548,130,9.0,21,27
1,3,88.6,168.8,64.1,48.8,2548,130,9.0,21,27
2,1,94.5,171.2,65.5,52.4,2823,152,9.0,19,26
3,2,99.8,176.6,66.2,54.3,2337,109,10.0,24,30
4,2,99.4,176.6,66.4,54.3,2824,136,8.0,18,22
...,...,...,...,...,...,...,...,...,...,...
200,-1,109.1,188.8,68.9,55.5,2952,141,9.5,23,28
201,-1,109.1,188.8,68.8,55.5,3049,141,8.7,19,25
202,-1,109.1,188.8,68.9,55.5,3012,173,8.8,18,23
203,-1,109.1,188.8,68.9,55.5,3217,145,23.0,26,27
204,-1,109.1,188.8,68.9,55.5,3062,141,9.5,19,25

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    str
 2   make               205 non-null    str
 3   fuel-type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       205 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               205 non-null    str
 19  stroke             205 non-null    str
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    str
 22  peak-rpm           205 non-null    str
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 41.8 KB

In [13]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [14]:
df.tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [18]:
df.sample(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
57,3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,...,70,4bbl,?,?,9.4,101,6000,17,23,13645
89,1,128,nissan,gas,std,two,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499
22,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6377
154,0,81,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62,4800,27,32,7898
107,0,161,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,11900
168,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116,4800,24,30,9639
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
114,0,?,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95,4150,25,25,17075
138,2,83,subaru,gas,std,two,hatchback,fwd,front,93.7,...,97,2bbl,3.62,2.36,9.0,69,4900,31,36,5118

In [19]:
df.shape

(205, 26)

In [20]:
df2 = df.sample(10)

In [22]:
df2.to_csv("data_01.csv")

In [24]:
s = pd.Series(data=[2, 6, 3, 9])
s.dtypes

dtype('int64')

In [ ]:
# symboling            int64        =>    Đúng
# normalized-losses    str          =>    Đúng
# make                 str          =>    Đúng
# fuel-type            str          =>    Đúng
# aspiration           str          =>    Đúng
# num-of-doors         str          =>    Đúng
# body-style           str          =>    Đúng
# drive-wheels         str          =>    Đúng
# engine-location      str          =>    Đúng
# wheel-base           float64      =>    Đúng
# length               float64      =>    Đúng
# width                float64      =>    Đúng
# height               float64      =>    Đúng
# curb-weight          int64        =>    Đúng
# engine-type          str          =>    Đúng
# num-of-cylinders     str          =>    Đúng
# engine-size          int64        =>    Đúng
# fuel-system          str          =>    Đúng
# bore                 str          =>    Đúng
# stroke               str          =>    Đúng
# compression-ratio    float64      =>    Đúng
# horsepower           str          =>    Đúng
# peak-rpm             str          =>    Đúng
# city-mpg             int64        =>    Đúng
# highway-mpg          int64        =>    Đúng
# price                str          =>    Đúng